source 'https://rubygems.org'

gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
gem 'pg', '~> 0.19.0'
gem 'puma', '~> 3.0'
gem 'uglifier', '>= 1.3.0'
gem 'jbuilder', '~> 2.5'
gem 'bcrypt', '~> 3.1.7'
gem 'carrierwave', '~> 0.11.2'
gem 'carrierwave-base64', '~> 2.3.3'
gem 'mini_magick', '~> 4.5.1'
gem 'redis', '~> 3.3.2'

group :development, :test do
  gem 'byebug', platform: :mri
end

group :development do
  gem 'web-console', '~> 3.4.0'
  gem 'listen', '~> 3.0.5'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'mini_racer', platforms: :ruby
